package Form;

import Connect.Ketnoi;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Mint
 */
public class NhaCungCap extends javax.swing.JFrame {

    private int index;
    DefaultTableModel model = new DefaultTableModel();
    Ketnoi k = new Ketnoi();
    private static String driver;
    private static String dburl;
    private static String user;
    private static String pass;
    static{
        try {
            BufferedReader out = new BufferedReader(new FileReader("change.txt"));
            driver = out.readLine();
            dburl = out.readLine();
            user = out.readLine();
            pass = out.readLine(); 
            Class.forName(driver);
        } catch (Exception e) {
        }
    }
    Connection cn;

    public NhaCungCap() {
        try {
            initComponents();
            setTitle("Nhà cung cấp");
            setLocationRelativeTo(null);
            k.connect();
            cn = DriverManager.getConnection(dburl,user,pass);
        } catch (SQLException ex) {
            Logger.getLogger(NhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhacc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMaNhaCC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhaCC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmaiil = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnTaoMoi = new javax.swing.JButton();
        btnMoFile = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnFisrt = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtTimKiem.setBackground(new java.awt.Color(231, 231, 231));
        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 8));

        btnTimKiem.setBackground(new java.awt.Color(22, 123, 255));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm\n");
        btnTimKiem.setBorderPainted(false);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(22, 123, 255));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText(">>");
        btnNext.setBorderPainted(false);

        btnPrev.setBackground(new java.awt.Color(22, 123, 255));
        btnPrev.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("<<");
        btnPrev.setBorderPainted(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        tblNhacc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblNhacc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhà cung cấp", "Tên Nhà Cung cấp", "Địa chỉ", "Email", "Điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhacc.setSelectionBackground(new java.awt.Color(22, 123, 255));
        tblNhacc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblNhaccMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhacc);
        if (tblNhacc.getColumnModel().getColumnCount() > 0) {
            tblNhacc.getColumnModel().getColumn(0).setMinWidth(70);
            tblNhacc.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblNhacc.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã nhà cung cấp");

        txtMaNhaCC.setBackground(new java.awt.Color(231, 231, 231));
        txtMaNhaCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNhaCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 4));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên nhà cung cấp");

        txtTenNhaCC.setBackground(new java.awt.Color(231, 231, 231));
        txtTenNhaCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenNhaCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 4));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Địa chỉ");

        txtDiaChi.setBackground(new java.awt.Color(231, 231, 231));
        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 4));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Email");

        txtEmaiil.setBackground(new java.awt.Color(231, 231, 231));
        txtEmaiil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmaiil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 4));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Số điện thoại");

        txtSDT.setBackground(new java.awt.Color(231, 231, 231));
        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 231, 231), 4));

        btnThem.setBackground(new java.awt.Color(46, 213, 115));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorderPainted(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTaoMoi.setBackground(new java.awt.Color(22, 123, 255));
        btnTaoMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTaoMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoMoi.setText("Tạo mới");
        btnTaoMoi.setBorderPainted(false);
        btnTaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMoiActionPerformed(evt);
            }
        });

        btnMoFile.setBackground(new java.awt.Color(255, 165, 2));
        btnMoFile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMoFile.setForeground(new java.awt.Color(255, 255, 255));
        btnMoFile.setText("Mở File");
        btnMoFile.setBorderPainted(false);
        btnMoFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoFileActionPerformed(evt);
            }
        });

        btnDong.setBackground(new java.awt.Color(47, 53, 66));
        btnDong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDong.setForeground(new java.awt.Color(255, 255, 255));
        btnDong.setText("Đóng");
        btnDong.setBorderPainted(false);
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 71, 87));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xoá");
        btnXoa.setBorderPainted(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnFisrt.setBackground(new java.awt.Color(22, 123, 255));
        btnFisrt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFisrt.setForeground(new java.awt.Color(255, 255, 255));
        btnFisrt.setText("|<");
        btnFisrt.setBorderPainted(false);
        btnFisrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFisrtActionPerformed(evt);
            }
        });

        btnLast.setBackground(new java.awt.Color(22, 123, 255));
        btnLast.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText(">|");
        btnLast.setBorderPainted(false);

        btnSua.setBackground(new java.awt.Color(255, 0, 204));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setBorderPainted(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(btnFisrt)
                                .addGap(31, 31, 31)
                                .addComponent(btnPrev)
                                .addGap(21, 21, 21)
                                .addComponent(btnNext)
                                .addGap(18, 18, 18)
                                .addComponent(btnLast)))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmaiil, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnMoFile, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFisrt, btnLast, btnNext, btnPrev});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnFisrt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(txtTimKiem))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmaiil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnMoFile)
                    .addComponent(btnDong)
                    .addComponent(btnXoa)
                    .addComponent(btnTaoMoi)
                    .addComponent(btnSua))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        try {
            int hoi = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát không ?", "Thoát", JOptionPane.YES_NO_OPTION);
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }
            Menu mn = new Menu();
            mn.setVisible(true);
            this.setVisible(false);
        } catch (HeadlessException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnDongActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFisrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFisrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFisrtActionPerformed

    private void tblNhaccMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaccMouseReleased
        try {
            index = tblNhacc.getSelectedRow();
            showDetail(index);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_tblNhaccMouseReleased

    private void btnTaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMoiActionPerformed
        try {
            clear();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnTaoMoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if (tblNhacc.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Trong bảng chưa có dữ liệu");
            return;
        } else {
            index = tblNhacc.getRowCount();
            for (int i = 0; i < index; i++) {
                if (tblNhacc.getValueAt(i, 0).toString().equalsIgnoreCase(txtTimKiem.getText())) {
                    showDetail(i);
                    JOptionPane.showMessageDialog(this, "Bạn đã tìm được Nhà cung cấp : " + tblNhacc.getValueAt(i, 1).toString());
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnMoFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoFileActionPerformed
        if ("Quangdzqua".equalsIgnoreCase(JOptionPane.showInputDialog("Mời nhập mã công ty để mở dữ liệu"))) {
            loadDataToTable();
            index = 0;
            showDetail(index);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Bạn đã nhập sai");
        }
    }//GEN-LAST:event_btnMoFileActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá không ?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            } else {
            }
            String sql = "delete from nhacungcap where mancc = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, txtMaNhaCC.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Đã xoá thành công nhà cung cấp : " + tblNhacc.getValueAt(index, 1));
            loadDataToTable();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            if (!checkNull()) {
                return;
            }
            try {
                Integer.parseInt(txtSDT.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại phải là số");
                return;
            }
            String sql = "insert into nhacungcap values(?,?,?,?,?)";
            PreparedStatement st;
            st = k.cn.prepareStatement(sql);
            st.setString(1, txtMaNhaCC.getText());
            st.setString(2, txtTenNhaCC.getText());
            st.setString(3, txtDiaChi.getText());
            st.setString(4, txtEmaiil.getText());
            st.setString(5, txtSDT.getText());
            st.executeUpdate();
            loadDataToTable();
        } catch (SQLException ex) {
            Logger.getLogger(NhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            if (!checkNull()) {
                return;
            }
            try {
                Integer.parseInt(txtSDT.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại phải là số");
                return;
            }
            String sql = "update nhacungcap set tenncc = ?, diachi = ?,email =?, dienthoai = ? where mancc = ?";
            PreparedStatement st = k.cn.prepareStatement(sql);
            st.setString(1, txtTenNhaCC.getText());
            st.setString(2, txtDiaChi.getText());
            st.setString(3, txtEmaiil.getText());
            st.setString(4, txtSDT.getText());
            st.setString(5, txtMaNhaCC.getText());
            if (tblNhacc.getValueAt(index, 0).toString().equalsIgnoreCase(txtMaNhaCC.getText())) {
                st.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Đã sửa thành công nhà cung cấp : " + txtTenNhaCC.getText());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Mã nhà cung cấp phải giống trong bảng");
            }
            loadDataToTable();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnFisrt;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoFile;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhacc;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmaiil;
    private javax.swing.JTextField txtMaNhaCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNhaCC;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
private void loadDataToTable() {
        try {
            model = (DefaultTableModel) tblNhacc.getModel();
            model.setRowCount(0);
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("select * from NhaCungcap");
            while (rs.next()) {
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                row.add(rs.getString(5));
                model.addRow(row);
            }
        } catch (SQLException e) {
            System.out.println("Lỗi tải dữ liệu");
        }
    }

    private void showDetail(int index) {
        txtMaNhaCC.setText(tblNhacc.getValueAt(index, 0).toString());
        txtTenNhaCC.setText(tblNhacc.getValueAt(index, 1).toString());
        txtDiaChi.setText(tblNhacc.getValueAt(index, 2).toString());
        txtEmaiil.setText(tblNhacc.getValueAt(index, 3).toString());
        txtSDT.setText(tblNhacc.getValueAt(index, 4).toString());
        tblNhacc.setRowSelectionInterval(index, index);
    }

    private void clear() {
        txtMaNhaCC.setText("");
        txtTenNhaCC.setText("");
        txtDiaChi.setText("");
        txtEmaiil.setText("");
        txtSDT.setText("");
    }

    private boolean checkNull() {
        if (txtMaNhaCC.getText().isEmpty()) {
            txtMaNhaCC.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Mã nhà cung cấp trống");
            return false;
        } else if (txtTenNhaCC.getText().isEmpty()) {
            txtTenNhaCC.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Tên nhà cung cấp trống");
            return false;
        } else if (txtDiaChi.getText().isEmpty()) {
            txtDiaChi.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Địa chỉ trống");
            return false;
        } else if (txtEmaiil.getText().isEmpty()) {
            txtEmaiil.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Email trống");
            return false;
        } else if (txtSDT.getText().isEmpty()) {
            txtSDT.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại trống");
            return false;
        } else if ((txtEmaiil.getText().endsWith(".com") || txtEmaiil.getText().endsWith(".COM") || txtEmaiil.getText().endsWith(".Com") || txtEmaiil.getText().endsWith(".COm") || txtEmaiil.getText().endsWith(".cOM") || txtEmaiil.getText().endsWith(".coM")) == false) {
            txtEmaiil.requestFocus();
            JOptionPane.showMessageDialog(this, "Email phải kết thúc bằng đuôi \".com\"");
            return false;
        } else {
            return true;
        }
    }

}
